;=====================================================================
;-| AI section |------------------------------------------------------
;---------------------------------------------------------------------
[Command]
name = "AI_1"
command = a,a,a,a
time = 0
[Command]
name = "AI_2"
command = a,a,a,b
time = 0
[Command]
name = "AI_3"
command = a,a,a,c
time = 0
[Command]
name = "AI_4"
command = a,a,b,a
time = 0
[Command]
name = "AI_5"
command = a,a,b,b
time = 0
[Command]
name = "AI_6"
command = a,a,b,c
time = 0
[Command]
name = "AI_7"
command = a,a,c,a
time = 0
[Command]
name = "AI_8"
command = a,a,c,b
time = 0
[Command]
name = "AI_9"
command = a,a,c,c
time = 0
[Command]
name = "AI_10"
command = a,b,a,a
time = 0
[Command]
name = "AI_11"
command = a,b,a,b
time = 0
[Command]
name = "AI_12"
command = a,b,a,c
time = 0
[Command]
name = "AI_13"
command = a,b,b,a
time = 0
[Command]
name = "AI_14"
command = a,b,b,b
time = 0
[Command]
name = "AI_15"
command = a,b,b,c
time = 0
[Command]
name = "AI_16"
command = a,b,c,a
time = 0
[Command]
name = "AI_17"
command = a,b,c,b
time = 0
[Command]
name = "AI_18"
command = a,b,c,c
time = 0
[Command]
name = "AI_19"
command = a,c,a,a
time = 0
[Command]
name = "AI_20"
command = a,c,a,b
time = 0
[Command]
name = "AI_21"
command = a,c,a,c
time = 0
[Command]
name = "AI_22"
command = a,c,b,a
time = 0
[Command]
name = "AI_23"
command = a,c,b,b
time = 0
[Command]
name = "AI_24"
command = a,b,b,c
time = 0
[Command]
name = "AI_25"
command = a,c,c,a
time = 0
[Command]
name = "AI_26"
command = a,c,c,b
time = 0
[Command]
name = "AI_27"
command = a,c,c,c
time = 0
[Command]
name = "AI_28"
command = b,a,a,a
time = 0
[Command]
name = "AI_29"
command = b,a,a,b
time = 0
[Command]
name = "AI_30"
command = b,a,a,c
time = 0
[Command]
name = "AI_31"
command = b,a,b,a
time = 0
[Command]
name = "AI_32"
command = b,a,b,b
time = 0
[Command]
name = "AI_33"
command = b,a,b,c
time = 0
[Command]
name = "AI_34"
command = b,a,c,a
time = 0
[Command]
name = "AI_35"
command = b,a,c,b
time = 0
[Command]
name = "AI_36"
command = b,a,c,c
time = 0
[Command]
name = "AI_37"
command = b,b,a,a
time = 0
[Command]
name = "AI_38"
command = b,b,a,b
time = 0
[Command]
name = "AI_39"
command = b,b,a,c
time = 0
[Command]
name = "AI_40"
command = b,b,b,a
time = 0
[Command]
name = "AI_41"
command = b,b,b,b
time = 0
[Command]
name = "AI_42"
command = b,b,b,c
time = 0
[Command]
name = "AI_43"
command = b,b,c,a
time = 0
[Command]
name = "AI_44"
command = b,b,c,b
time = 0
[Command]
name = "AI_45"
command = b,b,c,c
time = 0
[Command]
name = "AI_46"
command = b,c,a,a
time = 0
[Command]
name = "AI_47"
command = b,c,a,b
time = 0
[Command]
name = "AI_48"
command = b,c,a,c
time = 0
[Command]
name = "AI_49"
command = b,c,b,a
time = 0
[Command]
name = "AI_50"
command = b,c,b,b
time = 0

;---------------------------------------------------------------------------
;-| Super Combos |----------------------------------------------------------
[Command]
name = "MAX"
command = ~F,DF,DB,B,F,DF,DB,B,x
time = 40
[Command]
name = "MAX"
command = ~F,DF,DB,B,F,DF,DB,B,y
time = 40
[Command]
name = "MAX"
command = ~F,DF,DB,B,F,DF,DB,B,z
time = 40

[Command]
name = "fuzi_c"
command = ~50$B,F,B,F,c
time = 30
[Command]
name = "fuzi_b"
command = ~50$B,F,B,F,b
time = 30
[Command]
name = "fuzi_b"
command = ~50$B,F,B,F,c
time = 30
[Command]
name = "fuzi_a"
command = ~50$B,F,B,F,a
time = 30
[Command]
name = "fuzi_a"
command = ~50$B,F,B,F,b
time = 30
[Command]
name = "fuzi_a"
command = ~50$B,F,B,F,c
time = 30

[Command]
name = "QCF_3"
command = ~50$B,F,B,F,z
time = 30
[Command]
name = "QCF_2"
command = ~50$B,F,B,F,y
time = 30
[Command]
name = "QCF_2"
command = ~50$B,F,B,F,z
time = 30
[Command]
name = "QCF_1"
command = ~50$B,F,B,F,x
time = 30
[Command]
name = "QCF_1"
command = ~50$B,F,B,F,y
time = 30
[Command]
name = "QCF_1"
command = ~50$B,F,B,F, z
time = 30

;---------------------------------------------------------------------------
;-| Special Attacks |-------------------------------------------------------
[Command]
name = "ooityou_x"
command = ~F,DF,DB,B,F,x
time = 30
[Command]
name = "ooityou_y"
command = ~F,DF,DB,B,F,y
time = 30
[Command]
name = "ooityou_z"
command = ~F,DF,DB,B,F,z
time = 30
[Command]
name = "ooityou_x"
command = ~F,DF,D,DB,B,F,x
time = 35
[Command]
name = "ooityou_y"
command = ~F,DF,D,DB,B,F,y
time = 35
[Command]
name = "ooityou_z"
command = ~F,DF,D,DB,B,F,z
time = 35

;?X?[?p?[??????
[Command]
name = "zutuki_x"
command = ~50$B,F,x
time = 30
[Command]
name = "zutuki_y"
command = ~50$B,F,y
time = 30
[Command]
name = "zutuki_z"
command = ~50$B,F,z
time = 30

;?X?[?p?[?S????????
[Command]
name = "hyakkan_a"
command = ~50$D,U,a
time = 30
[Command]
name = "hyakkan_b"
command = ~50$D,U,b
time = 30
[Command]
name = "hyakkan_c"
command = ~50$D,U,c
time = 30

[Command]
name = "rapidspank_x"
command = x,x,x
time = 30
[Command]
name = "rapidspank_y"
command = y,y,y
time = 30
[Command]
name = "rapidspank_z"
command = z,z,z
time = 35


;----------------------------------------------------------------------
;-| Basic Motions |----------------------------------------------------
;Air Grapple
[Command]
name = "AT"
command = x+y
time = 3
[Command]
name = "AT"
command = y+z
time = 3
[Command]
name = "AT"
command = x+z
time = 3
[Command]
name = "AT"
command = a+c
time = 3
[Command]
name = "AT"
command = a+b
time = 3
[Command]
name = "AT"
command = b+c
time = 3

; Front Grapple
[Command]
name = "FT"
command = x+y
time = 1

[Command]
name = "FT"
command = y+z
time = 1

[Command]
name = "FT"
command = x+z
time = 1

[Command]
name = "BT"
command = a+c
time = 1

[Command]
name = "BT"
command = a+b
time = 1

[Command]
name = "BT"
command = b+c
time = 1

; Zero Counter
[Command]
name = "ZC"
command = /$F, b+y
time = 3

[Command]
name = "ZC"
command = /$F, c+z
time = 3

;---------------------------------------------------------------------------
;-| Double Tap |------------------------------------------------------------
[Command]
name = "FF"
command = F, F
time = 10
[Command]
name = "BB"
command = B, B
time = 10

[Command]
name = "recovery"
command = x+a
time = 1

[Command]
name = "Shaking"
command = B, F
time = 10
[Command]
name = "Shaking"
command = F, B
time = 10

;---------------------------------------------------------------------------
;-| Dir + Button |----------------------------------------------------------
[command]
name = "fwd_b"
command = /F, b
time = 1
[command]
name = "fwd_c"
command = /F, c
time = 1

;---------------------------------------------------------------------------
;-| Single Button |---------------------------------------------------------
[Command]
name = "electric1"
command = x
time = 1
[Command]
name = "electric2"
command = y
time = 1
[Command]
name = "electric3"
command = z
time = 1

[Command]
name = "a"
command = a
time = 1
[Command]
name = "b"
command = b
time = 1
[Command]
name = "c"
command = c
time = 1
[Command]
name = "x"
command = x
time = 1
[Command]
name = "y"
command = y
time = 1
[Command]
name = "z"
command = z
time = 1
[Command]
name = "s"
command = s
time = 1

;---------------------------------------------------------------------------
;-| Hold Button |-----------------------------------------------------------
[Command]
name = "hold_x"
command = /x
time = 1
[Command]
name = "hold_y"
command = /y
time = 1
[Command]
name = "hold_z"
command = /z
time = 1
[Command]
name = "hold_a"
command = /a
time = 1
[Command]
name = "hold_b"
command = /b
time = 1
[Command]
name = "hold_c"
command = /c
time = 1
[Command]
name = "hold_s"
command = /s
time = 1

;---------------------------------------------------------------------------
;-| Hold Dir |--------------------------------------------------------------
[Command]
name = "F"
command = F
time = 1
[Command]
name = "B"
command = B
time = 1
[Command]
name = "U"
command = U
time = 1
[Command]
name = "D"
command = D
time = 1

[Command]
name = "holdfwd"
command = /$F
time = 1
[Command]
name = "holdback"
command = /$B
time = 1
[Command]
name = "holdup"
command = /$U
time = 1
[Command]
name = "holddown"
command = /$D
time = 1

;---------------------------------------------------------------------------
;===========================================================================
[Statedef -1]
;===========================================================================
;---------------------------------------------------------------------------
;===========================================================================
; Super Combos
;===========================================================================
[State -1, salto agarre nalga 3]
type = ChangeState
value = 3220
triggerall = command = "fuzi_c"
triggerall = power >= 3000
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, salto agarre nalga 2]
type = ChangeState
value = 3210
triggerall = command = "fuzi_b"
triggerall = power >= 2000
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, salto agarre nalga 1]
type = ChangeState
value = 3200
triggerall = command = "fuzi_a"
triggerall = Power >= 1000 
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact

[State -1, super aplaste Lv1]
type = ChangeState
value = 3100
triggerall = command = "MAX"
triggerall = Power >= 3000 
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact

[State -1, kbzas varias Lv3]
type = ChangeState
value = 3020
triggerall = command = "QCF_3"
triggerall = power >= 3000
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, kbzas varias Lv2]
type = ChangeState
value = 3010
triggerall = command = "QCF_2"
triggerall = power >= 2000
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, kbzas varias Lv1]
type = ChangeState
value = 3000
triggerall = command = "QCF_1"
triggerall = Power >= 1000 
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact

;===========================================================================
; Special Attacks
;===========================================================================
[State -1, grab and smash W]
type = ChangeState
value = 1300
triggerall = command = "ooityou_x"
triggerall = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, grab and smash M]
type = ChangeState
value = 1310
triggerall = command = "ooityou_y"
triggerall = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, grab and smash S]
type = ChangeState
value = 1320
triggerall = command = "ooityou_z"
triggerall = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact

[State -1, vertical W]
type = ChangeState
value = 1200
triggerall = command = "hyakkan_a"
triggerall = StateType != A
trigger1 = Ctrl = 1
trigger2 = stateno = 40
trigger3 = stateno = 430 && MoveContact
[State -1, vertical M]
type = ChangeState
value = 1210
triggerall = command = "hyakkan_b"
triggerall = StateType != A
trigger1 = Ctrl = 1
trigger2 = stateno = 40
trigger3 = stateno = 430 && MoveContact
[State -1, vertical S]
type = ChangeState
value = 1220
triggerall = command = "hyakkan_c"
triggerall = StateType != A
trigger1 = Ctrl = 1
trigger2 = stateno = 40
trigger3 = stateno = 430 && MoveContact

[State -1, zutuki W]
type = ChangeState
value = 1100
triggerall = command = "zutuki_x"
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, zutuki M]
type = ChangeState
value = 1110
triggerall = command = "zutuki_y"
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact
[State -1, zutuki S]
type = ChangeState
value = 1120
triggerall = command = "zutuki_z"
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 430 && MoveContact

[State -1, manotazo W]
type = ChangeState
value = 1000
triggerall = command = "rapidspank_x"
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 200 && MoveContact
trigger3 = stateno = 210 && MoveContact
trigger4 = stateno = 225 && MoveContact
trigger5 = stateno = 245 && MoveContact
trigger6 = stateno = 400 && MoveContact
[State -1, manotazo M]
type = ChangeState
value = 1010
triggerall = command = "rapidspank_y"
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 200 && MoveContact
trigger3 = stateno = 210 && MoveContact
trigger4 = stateno = 225 && MoveContact
trigger5 = stateno = 245 && MoveContact
trigger6 = stateno = 400 && MoveContact
[State -1, manotazo S]
type = ChangeState
value = 1020
triggerall = command = "rapidspank_z"
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger2 = stateno = 200 && MoveContact
trigger3 = stateno = 210 && MoveContact
trigger4 = stateno = 225 && MoveContact
trigger5 = stateno = 245 && MoveContact
trigger6 = stateno = 400 && MoveContact

;===========================================================================
; Run
;===========================================================================
[State -1, adelante]
type = ChangeState
value = 100
triggerall = Command = "FF"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger1 = StateNo != 100

[State -1, atras]
type = ChangeState
value = 105
trigger1 = command = "BB"
trigger1 = statetype = S
trigger1 = ctrl = 1

;===========================================================================
; Grapple Attacks
;===========================================================================
[State -1, Reverse]
type = ChangeState
value = 800
triggerall = statetype = S
triggerall = ctrl = 1
trigger1 = command = "BT"

[State -1, Frontal]
type = ChangeState
value = 850
triggerall = statetype = S
triggerall = ctrl = 1
trigger1 = command = "FT"

[State -1, Air]
type = ChangeState
value = 900
triggerall = statetype = A
triggerall = ctrl = 1
trigger1 = command = "AT"

;===========================================================================
; CvS / SFZ Skills
;===========================================================================
[State -1]
type = ChangeState
value = 2600
triggerall = Command = "ZC"
triggerall = p2bodydist X = [-50,50]
triggerall = Power >= 1000
triggerall = statetype != A
trigger1 = StateNo = [150,153]  
ignorhitpause = 1

;===========================================================================
; Dir + Button
;===========================================================================
[State -1, F+MK]
type = ChangeState
value = 300
triggerall = command = "fwd_b"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

[State -1, F+SK]
type = ChangeState
value = 310
triggerall = command = "fwd_c"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

;===========================================================================
; Standing Attacks
;===========================================================================
[State -1, WP]
type = ChangeState
value = 200
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

[State -1, MP]
type = ChangeState
value = 210
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

[State -1, SP]
type = ChangeState
value = 220
triggerall = command = "z"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

[State -1, WK]
type = ChangeState
value = 230
triggerall = command = "a"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

[State -1, MK]
type = ChangeState
value = 240
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

[State -1, SK]
type = ChangeState
value = 250
triggerall = command = "c"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1

;===========================================================================
; Crouching Attacks
;===========================================================================
[State -1, WP]
type = ChangeState
value = 400
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1

[State -1, MP]
type = ChangeState
value = 410
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1

[State -1, SP]
type = ChangeState
value = 420
triggerall = command = "z"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1

[State -1, WK]
type = ChangeState
value = 430
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1

[State -1, MK]
type = ChangeState
value = 440
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1

[State -1, SK]
type = ChangeState
value = 450
triggerall = command = "c"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1

;===========================================================================
; Jumping Attacks
;===========================================================================
[State -1, WP]
type = ChangeState
value = 600
trigger1 = command = "x"
trigger1 = statetype = A
trigger1 = ctrl = 1

[State -1, MP]
type = ChangeState
value = 610
trigger1 = command = "y"
trigger1 = statetype = A
trigger1 = ctrl = 1

[State -1, SP]
type = ChangeState
value = 620
trigger1 = command = "z"
trigger1 = statetype = A
trigger1 = ctrl = 1

[State -1, WK]
type = ChangeState
value = 630
trigger1 = command = "a"
trigger1 = statetype = A
trigger1 = ctrl = 1

[State -1, MK]
type = ChangeState
value = 640
trigger1 = command = "b"
trigger1 = statetype = A
trigger1 = ctrl = 1

[State -1, SK]
type = ChangeState
value = 650
trigger1 = command = "c"
trigger1 = statetype = A
trigger1 = ctrl = 1

;===========================================================================
; Burla
;===========================================================================
[State -1]
type = ChangeState
value = 195
triggerall = !var(59)
triggerall = command = "s"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1


;---------------------------------------------------------------------------
;===========================================================================
;---------------------------------------------------------------------------
;                         A I   S E C T I O N .
;---------------------------------------------------------------------------
;===========================================================================
;---------------------------------------------------------------------------
[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1" || command = "AI_2" || command = "AI_3" || command = "AI_4" || command = "AI_5"
trigger2 = command = "AI_6" || command = "AI_7" || command = "AI_8" || command = "AI_9" || command = "AI_10"
trigger3 = command = "AI_11" || command = "AI_12" || command = "AI_13" || command = "AI_14" || command = "AI_15"
trigger4 = command = "AI_16" || command = "AI_17" || command = "AI_18" || command = "AI_19" || command = "AI_20"
trigger5 = command = "AI_21" || command = "AI_22" || command = "AI_23" || command = "AI_24" || command = "AI_25"
trigger6 = command = "AI_26" || command = "AI_27" || command = "AI_28" || command = "AI_29" || command = "AI_30"
trigger7 = command = "AI_31" || command = "AI_32" || command = "AI_33" || command = "AI_34" || command = "AI_35"
trigger8 = command = "AI_36" || command = "AI_37" || command = "AI_38" || command = "AI_39" || command = "AI_40"
trigger9 = command = "AI_41" || command = "AI_42" || command = "AI_43" || command = "AI_44" || command = "AI_45"
trigger10 = command = "AI_46" || command = "AI_47" || command = "AI_48" || command = "AI_49" || command = "AI_50"
var(59) = 10

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1" || command = "AI_2" || command = "AI_3" || command = "AI_4" || command = "AI_5"
trigger2 = command = "AI_6" || command = "AI_7" || command = "AI_8" || command = "AI_9" || command = "AI_10"
trigger3 = command = "AI_11" || command = "AI_12" || command = "AI_13" || command = "AI_14" || command = "AI_15"
trigger4 = command = "AI_16" || command = "AI_17" || command = "AI_18" || command = "AI_19" || command = "AI_20"
trigger5 = command = "AI_21" || command = "AI_22" || command = "AI_23" || command = "AI_24" || command = "AI_25"
trigger6 = command = "AI_26" || command = "AI_27" || command = "AI_28" || command = "AI_29" || command = "AI_30"
trigger7 = command = "AI_31" || command = "AI_32" || command = "AI_33" || command = "AI_34" || command = "AI_35"
var(59) = 9

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1" || command = "AI_2" || command = "AI_3" || command = "AI_4" || command = "AI_5"
trigger2 = command = "AI_6" || command = "AI_7" || command = "AI_8" || command = "AI_9" || command = "AI_10"
trigger3 = command = "AI_11" || command = "AI_12" || command = "AI_13" || command = "AI_14" || command = "AI_15"
trigger4 = command = "AI_16" || command = "AI_17" || command = "AI_18" || command = "AI_19" || command = "AI_20"
trigger5 = command = "AI_21" || command = "AI_22" || command = "AI_23" || command = "AI_24" || command = "AI_25"
var(59) = 8

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1" || command = "AI_2" || command = "AI_3"
trigger2 = command = "AI_6" || command = "AI_7" || command = "AI_8"
trigger3 = command = "AI_11" || command = "AI_12" || command = "AI_13"
trigger4 = command = "AI_16" || command = "AI_17" || command = "AI_18"
var(59) = 6

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1" || command = "AI_2"
trigger2 = command = "AI_6" || command = "AI_7"
trigger3 = command = "AI_11" || command = "AI_12"
var(59) = 5

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1" || command = "AI_2"
trigger2 = command = "AI_6" || command = "AI_7"
var(59) = 4

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1"
trigger2 = command = "AI_6"
var(59) = 3

[State -3]
type = Varset
triggerall = !var(59) ; Check the AI flag
trigger1 = alive
trigger1 = stateno < 5500
trigger1 = command = "AI_1"
var(59) = 2

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
trigger1 = roundstate>2
trigger2 = !alive
trigger3 = stateno = 5500
trigger4 = AILevel = 1
;trigger5 = teammode = simul
v = 59
value = 0
ignorehitpause = 1
persistent = 1

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = gamemode = "survival"
trigger1 = AILevel = 2 || AILevel = 3 || AILevel = 4
v = 59
value = 2

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = teammode = single
triggerall = gamemode != "survival"
trigger1 = matchno = [1,4] && (AILevel = 5 || AILevel = 6 || AILevel = 7)
trigger2 = matchno = 10 && (AILevel = 2 || AILevel = 3)
v = 59
value = 3

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = gamemode = "survival"
trigger1 = AILevel = 5 || AILevel = 6
v = 59
value = 4

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = gamemode = "survival"
trigger1 = AILevel = 7 || AILevel = 8
v = 59
value = 5

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = teammode = single
triggerall = gamemode != "survival"
trigger1 = (matchno = [5,9] && (AILevel = 5 || AILevel = 6 || AILevel = 7)) || (matchno = 10 && (AILevel = 1 || AILevel = 2 || AILevel = 3))
v = 59
value = 6

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = teammode = single
triggerall = gamemode != "survival"
trigger1 = matchno = 10 && (AILevel = 5 || AILevel = 6 || AILevel = 7)
v = 59
value = 8

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = teammode = single
triggerall = gamemode != "survival"
trigger1 = matchno < 10 && AILevel = 8
v = 59
value = 9

[State OFF]
type = VarSet
triggerall = ishometeam && teamside != 1 
triggerall = teammode = single
triggerall = gamemode != "survival"
trigger1 = matchno = 10 && AILevel = 8
v = 59
value = 10

; ---------------------------------------------------------------------------------

;Counter
[State -1, blocking Flag]
Type = VarSet
triggerall = fvar(27) = 0
triggerall = roundstate = 2
trigger1 = (stateno = [4000,4199])
fvar(27) = 1
IgnoreHitPause = 1

;Counter
[State -1, blocking Flag Re]
Type = VarSet
triggerall= fvar(27) != 0
trigger1 = Enemynear,ctrl || Enemynear,movetype = H || movetype = A
trigger2 = Enemynear,life <= 0 || p2bodydist X > 90 || stateno = 800
fvar(27) = 0
IgnoreHitPause = 1

[State -1, Nomal Jump]
Type = ChangeState
value = 44
triggerall = Var(59)
triggerall = roundstate = 2
triggerall = StateType != A
triggerall = ctrl
triggerall = EnemyNear, NumProj != 0
trigger1 = random <= 999
trigger1 = p2bodydist x > 150

[State -1, Nomal Jump]
Type = ChangeState
value = 42
triggerall = Var(59)
triggerall = roundstate = 2
triggerall = StateType != A
triggerall = ctrl || stateno = 16 || stateno = 21 || stateno = 22 || (stateno = 100 && animelemtime(2) >1) || stateno = 101
triggerall = !inguarddist
trigger1 = EnemyNear,movetype != H || EnemyNear,stateno = [120,159]
trigger1 = P2BodyDist X = [85,100]
trigger1 = random <= 20
;trigger2 = p2bodydist x > 200
;trigger2 = random <= 999

;recover
[State -1,rev]
type = ChangeState
value = 5210
triggerall = Var(59)
triggerall = !var(16)
triggerall = roundstate = 2
triggerall = Alive
triggerall = CanRecover
triggerall = Vel Y > -1
triggerall = Pos Y >= -40
triggerall = StateNo = 5050
trigger1 = random = [150,200]

;Chain combo
[State -1]; Chain
type = ChangeState
value = 240
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = P2BodyDist X <= 40
trigger1 = ctrl
trigger1 = p2statetype != A && p2statetype != L
trigger1 = p2movetype != H
;Chain combo
[State -1]; Chain
type = ChangeState
value = 230
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = P2BodyDist X <= 40
trigger1 = ctrl
trigger1 = p2statetype != A && p2statetype != L
trigger1 = p2movetype != H
[State -1]; Chain
type = ChangeState
value = 210
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = P2BodyDist X <= 40
trigger1 = ctrl
trigger1 = p2statetype != C && p2statetype != L
trigger1 = p2movetype != H
[State -1]; Chain
type = ChangeState
value = 200
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = movehit
trigger1 = stateno = 210 || stateno = 230 || stateno = 240
[State -1, WP AI]; Chain
type = ChangeState
value = 430
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = movehit
trigger1 = stateno = 200
[State -1, MP AI]; Chain alt
type = ChangeState
value = 440
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = movehit
trigger1 = stateno = 200
[State -1, MP AI]; Chain
type = ChangeState
value = 400
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = movehit
trigger1 = stateno = 430 || stateno = 440
[State -1, SP AI]; Chain
type = ChangeState
value = 1000
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = movecontact
trigger1 = stateno = 400
[State -1, SP AI]; Chain
type = ChangeState
value = 1010
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = movecontact
trigger1 = stateno = 400
[State -1, SP AI]; Chain
type = ChangeState
value = 1020
triggerall = var(59) && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = statetype != A
triggerall = p2statetype != A
triggerall = movecontact
trigger1 = stateno = 400

[State -1]
type = ChangeState
value = 1120
triggerall = random < var(59)*70
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2statetype = L
trigger1 = p2bodydist X = [100,250]
[State -1]
type = ChangeState
value = 1110
triggerall = random < var(59)*70
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2statetype = L
trigger1 = p2bodydist X = [70,100]
[State -1]
type = ChangeState
value = 1100
triggerall = random < var(59)*70 && AILevel > 3
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2movetype = A && EnemyNear, NumProj = 0
trigger1 = p2bodydist X = [-5,100]

[State -1]
type = ChangeState
value = 1220
triggerall = random < var(59)*60 && AILevel > 3
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2bodydist X = [40,60]

[State -1]
type = ChangeState
value = 1320
triggerall = random < var(59)*10 && AILevel > 3
triggerall = statetype != A
triggerall = p2statetype = S
trigger1 = ctrl
trigger1 = p2bodydist X = [-5,60]

[State -1]
type = ChangeState
value = 3220
triggerall = random < var(59)*10
triggerall = statetype != A
trigger1 = power >= 3000
trigger1 = movehit
trigger1 = ctrl
trigger1 = p2bodydist X = [-5,40]
[State -1]
type = ChangeState
value = 3210
triggerall = random < var(59)*10
triggerall = statetype != A
trigger1 = power >= 2000
trigger1 = movehit
trigger1 = ctrl
trigger1 = p2bodydist X = [-5,40]
[State -1]
type = ChangeState
value = 3200
triggerall = random < var(59)*10
triggerall = statetype != A
trigger1 = power >= 1000
trigger1 = movehit
trigger1 = ctrl
trigger1 = p2bodydist X = [-5,40]

[State -1]
type = ChangeState
value = 3020
triggerall = random < var(59)*70
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2movetype = A
trigger1 = power >= 3000
trigger1 = p2bodydist X = [40,70]
[State -1]
type = ChangeState
value = 3010
triggerall = random < var(59)*70
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2movetype = A
trigger1 = power >= 2000
trigger1 = p2bodydist X = [40,70]
[State -1]
type = ChangeState
value = 3000
triggerall = random < var(59)*70
triggerall = statetype != A
trigger1 = ctrl
trigger1 = p2movetype = A
trigger1 = power >= 1000
trigger1 = p2bodydist X = [40,70]

; ---------------------------------

[State -3]; Guard
type = ChangeState
value = 130
triggerall = var(59)
triggerall = p2statetype != C
triggerall = inguarddist
trigger1 = statetype != A && ctrl
[State -3]
type = ChangeState
value = 131
triggerall = var(59)
triggerall = p2statetype = C
triggerall = inguarddist
trigger1 = statetype != A && ctrl
[State -3]
type = ChangeState
value = 132
triggerall = var(59)
triggerall = inguarddist
trigger1 = statetype = A && ctrl


[State -1]
type = ChangeState
value = 250
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
triggerall = P2BodyDist X <= 60
trigger1 = statetype != A
trigger1 = ctrl
trigger1 = p2statetype = A && p2statetype != L
trigger1 = p2movetype != H

[State -1]
type = ChangeState
value = 220
triggerall = random < var(59)*100 && roundstate = 2
triggerall = P2BodyDist X <= 25
trigger1 = statetype != A
trigger1 = ctrl
trigger1 = p2statetype = A
trigger1 = p2movetype = H
trigger1 = p2bodydist Y < -30
[State -1]
type = ChangeState
value = 420
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
trigger1 = statetype != A
trigger1 = ctrl
trigger1 = p2statetype != A && p2statetype != L
trigger1 = p2movetype = H
trigger1 = p2bodydist X = [26,30]
[State -1]
type = ChangeState
value = 220
triggerall = random < var(59)*100 && roundstate = 2
triggerall = P2BodyDist X <= 25
trigger1 = statetype != A
trigger1 = ctrl 
trigger1 = p2statetype = A
trigger1 = p2movetype = H
trigger1 = p2bodydist Y = [-70,20]
[State -1]
type = ChangeState
value = 200
triggerall = random < var(59)*100 && roundstate = 2
trigger1 = statetype != A
trigger1 = ctrl 
trigger1 = p2statetype = A
trigger1 = p2bodydist X = [26,60]
trigger1 = p2bodydist Y = [-70,20]
[State -1]
type = ChangeState
value = 430
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
trigger1 = statetype != A
trigger1 = ctrl
trigger1 = p2statetype != A && p2statetype != L
trigger1 = p2bodydist X = [-5,50]
trigger1 = p2movetype != H || p2bodydist X < 40
trigger1 = p2stateno != [150,153]
[State -1]
type = ChangeState
value = 440
triggerall = random < var(59)*100 && AILevel > 3 && roundstate = 2 && teammode = single
trigger1 = statetype != A
trigger1 = ctrl 
trigger1 = p2statetype != A && p2statetype != L
trigger1 = p2bodydist X = [-5,50]
trigger1 = p2stateno != [152,153]
[State -1]
type = ChangeState
value = 600
triggerall = random < var(59)*100 && roundstate = 2
triggerall = statetype = A
trigger1 = ctrl 
trigger1 = Vel X != 0
trigger1 = p2statetype = A
trigger1 = p2bodydist X = [-5,50]
trigger1 = p2bodydist Y = [-70,60]
[State -1]
type = ChangeState
value = 620
triggerall = random < var(59)*100 && roundstate = 2
triggerall = statetype = A
trigger1 = ctrl
trigger1 = p2bodydist X = [-5,50]
trigger1 = p2bodydist Y = [0,70]
trigger1 = p2statetype = A
[State -1]
type = ChangeState
value = 630
triggerall = random < var(59)*100 && roundstate = 2
triggerall = statetype = A
trigger1 = ctrl 
trigger1 = p2bodydist X = [-5,20]
trigger1 = p2bodydist Y = [-60,100]
trigger1 = p2statetype = A
[State -1]
type = ChangeState
value = 640
triggerall = random < var(59)*100 && roundstate = 2
triggerall = statetype = A
trigger1 = ctrl
trigger1 = p2statetype = A
trigger1 = p2bodydist X = [-5,30]
trigger1 = p2bodydist Y = [-90,0]
[State -1]
type = ChangeState
value = 650
triggerall = random < var(59)*100 && roundstate = 2
triggerall = statetype = A
trigger1 = ctrl
trigger1 = p2bodydist X = [-5,80]
trigger1 = p2bodydist Y = [0,110]
trigger1 = p2statetype = A

;===========================================================================
;                                                   E N D   O F   F I L E .
;===========================================================================